# Generated by Django 5.2.18 on 2026-10-09 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_admin', models.BooleanField(default=False)),
                ('password_index', models.CharField(max_length=64, unique=True)),
                ('encrypted_password', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_failure', models.DateTimeField()),
                ('blocked_until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='ballot',
            name='choices',
            field=models.ManyToManyField(through='election.Choice', to='election.candidate'),
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_open', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_election')],
            },
        ),
        migrations.AddField(
            model_name='ballot',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='election.identity'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('ballot', 'candidate'), name='unique_ballot_candidate'),
        ),
    ]
