services:
  voting-web:
    build: .
    env_file: .env
    environment:
      DEBUG: "0"
      DATABASE_PATH: /data/db.sqlite3
    volumes:
      - ./data:/data
      - ./fonts:/app/fonts:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: wordpress_wordpress_net
    external: true
